spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.86.236:3306/ocr
#    url: jdbc:mysql://192.168.1.122:3306/ocr
    url: jdbc:mysql://150.158.45.111:3306/ocr?useUnicode=true&characterEncoding=utf8&useSSL=false
#    url: jdbc:mysql://192.168.33.16:3306/ocr?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 20MB #单个文件最大为20M
      max-request-size: 20MB #单次请求文件总数大小为20M
logging:
  level:
    root: warn
    com.ryo.ocr.dao: trace
  pattern:
    console: '%p%m%n'
server:
  port: 9888
web:
  upload-path: /Users/ryo/data/
#  upload-path: /tmp/ocrData/
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}